[build]
  command = "DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 